apiVersion: apps/v1
kind: Deployment
metadata:
  name: v4as
  namespace: v4a
  labels:
    k8s-app: v4as
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: v4as
  template:
    metadata:
      labels:
        k8s-app: v4as
    spec:
      containers:
        - name: v4as
          image: ivukotic/v4a:latest
          args: ["-t", "3600"]
          env:
            - name: VARNISH_MEM
              value: "32G"
            - name: VARNISH_TRANSIENT_MEM
              value: "2G"
          ports:
            - containerPort: 80
              hostPort: 6081
            - containerPort: 3401
              hostPort: 3401
              protocol: UDP
          resources:
            requests:
              cpu: "4"
              memory: "33Gi"
            limits:
              cpu: "48"
              memory: "48Gi"

      nodeSelector:
        varnish: frontier
