name: DockerPush

on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.1
        with:
          image: ivukotic/v4a
          tags: latest, ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
